import Head from "next/head";
import { FunctionComponent } from "react";
import { useState } from "react";
import { UseCustomFormProvider } from "../modules/form/hooks/useCustomForm";
import {
  PersoInfo,
  PlanInfo,
  ChosenAddOns,
  Summary,
} from "../modules/form/screen";

type Addons = "onlineServices" | "largerStorage" | "customProfile";

interface StoredData {
  name: string;
  email: string;
  phoneNumber: string;
  subscriptionType: "monthly" | "annualy";
  plan: "arcade" | "advanced" | "pro";
  addons: Addons[];
}

const initialValues: StoredData = {
  addons: [],
  email: "",
  name: "",
  phoneNumber: "",
  plan: "pro",
  subscriptionType: "monthly",
};

export default function Home() {
  const [selectedStep, setSelectedStep] = useState<number>(1);
  interface NavItemProps {
    name: string;
    stepNumber: number;
  }

  const NavItem: FunctionComponent<NavItemProps> = ({ name, stepNumber }) => {
    const isSelected = selectedStep === stepNumber;

    return (
      <div
        className="flex my-2 cursor-pointer w-64"
        onClick={() => setSelectedStep(stepNumber)}
      >
        <h1 className="mx-4 border rounded-full px-4 py-2 flex items-center justify-center">
          {stepNumber}
        </h1>
        <div>
          <p>STEP {stepNumber}</p>
          <h2>{name}</h2>
        </div>
      </div>
    );
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="flex">
          <nav className="bg-scroll p-4 m-4 rounded-lg bg-gradient-to-r from-sky-500 to-indigo-500 border-black border-2">
            <ol>
              <li>
                <NavItem name="your Info" stepNumber={1} />
              </li>
              <li>
                <NavItem name="Select Plan" stepNumber={2} />
              </li>
              <li>
                <NavItem name="add-ons" stepNumber={3} />
              </li>
              <li>
                <NavItem name="Summary" stepNumber={4} />
              </li>
            </ol>
          </nav>
          <main>
            <UseCustomFormProvider<StoredData> initialValues={initialValues}>
              {selectedStep === 1 && <PersoInfo />}
              {selectedStep === 2 && <PlanInfo />}
              {selectedStep === 3 && <ChosenAddOns />}
              {selectedStep === 4 && <Summary />}
            </UseCustomFormProvider>
          </main>
        </div>
      </div>
    </>
  );
}
